#!/bin/bash

rm -rf kern
mkdir -p kern

args=("$@")

pad_num=${args[1]:-3}

pad_with_zeros() {
    if [[ ! "$1" =~ ^[0-9]+$ ]]; then
        echo "Error: Input is not a valid number."
        return 1
    fi
    num=$(echo "$1" | sed 's/^0*//')
    printf "%0${pad_num}d" "$num"
}

swap_lines() {
    local string=${1:-$(</dev/stdin)}
    # declare string=${*:-$(</dev/stdin)}
    local swapped_string=$(echo -e "$string" | awk 'NR==1{first=$0; next} NR==2{print $0 ORS first; next} {print}')
    echo -e "$swapped_string"
}

for file in "${args[0]}"/*.{mxl,xml,musicxml}; do
    if [[ -f "$file" ]]; then
        filename=$(basename -- "$file")
        extension="${filename##*.}"
        filename="${filename%.*}"
        if [[ "$extension" == "mxl" ]]; then
            rm -rf tmp
            mkdir -p tmp
            # unzip -o "$file" -d tmp &> /dev/null
            ditto -V -x -k --sequesterRsrc --rsrc "$file" tmp &> /dev/null
            pattern="tmp/*.xml"
            xml_files=( $pattern )
            xml_file=${xml_files[0]}
        else
            xml_file="$file"
        fi
        unzip -o "$file" -d tmp &> /dev/null
        pattern="tmp/*.xml"
        kern_filename=$(php slugify.php "$(echo "$filename" | sed "s/Schiorring - //")"   )
        num=$(echo "$kern_filename" | grep -o '^[0-9]\+' | sed 's/^0*//')
        padded_num=$(pad_with_zeros "$num")
        kern_filename="${padded_num}$(echo "$kern_filename" | sed 's/[0-9]*//g')"
        kern_filename="$kern_filename.krn"
        echo "$kern_filename"
        musicxml2hum "$xml_file" | \
            extractxx -f 1,3,2,4,5,6,7,8,9 | \
            cat <(echo -e -n "!!!ONM: $num\n") - | \
            swap_lines | \
            sed "s/^!!!OMV:/!!!OTL@@DA:/" | \
            sed "s/^!!!OTL:/!!!OPR@@DA:/" | \
            sed "s/^!!!OPR@@DA: Choral Bog/!!!OPR@@DA: Choral-Bog/" | \
            cat <(echo -e -n "!!!CDT: 1743-1798\n") - | \
            cat <(echo -e -n "!!!COM: Schiørring, Niels\n") - | \
            sed "s/!!!system-decoration:.*/!!!system-decoration: {(s1,s2,s3,s4)}{(s5,s6)}{(s7,s8)}/g" | \
            cat - <(echo -e -n "!!!AGN: chorale\n") | \
            cat - <(echo -e -n "!!!EED: Derek Remeš\n") | \
            cat - <(echo -e -n "!!!EED2: Victor Phan\n") | \
            cat - <(echo -e -n "!!!END: $(date '+%Y/%m/%d')\n") | \
            cat - <(echo -e -n "!!!ENC: Wolfgang Drescher\n") | \
            cat - <(echo -e -n "!!!EEV: $(date '+%Y/%m/%d')\n") | \
            cat - <(echo -e -n "!!!title: @{ONM}. @{OTL}\n") | \
            grep -v '^*I' | \
            awk '!/^([\t*]+)$/' | \
            echo -ne "$(cat)" \
            > "kern/$kern_filename"
    fi
done

rm -rf tmp
