#!/bin/bash

rm -rf kern
mkdir -p kern

args=("$@")

pad_num=${args[1]:-3}

pad_with_zeros() {
    if [[ ! "$1" =~ ^[0-9]+$ ]]; then
        echo "Error: Input is not a valid number."
        return 1
    fi
    num=$(echo "$1" | sed 's/^0*//')
    printf "%0${pad_num}d" "$num"
}

for file in "${args[0]}"/*.{mxl,xml,musicxml}; do
    if [[ -f "$file" ]]; then
        filename=$(basename -- "$file")
        extension="${filename##*.}"
        filename="${filename%.*}"
        if [[ "$extension" == "mxl" ]]; then
            rm -rf tmp
            mkdir -p tmp
            # unzip -o "$file" -d tmp &> /dev/null
            ditto -V -x -k --sequesterRsrc --rsrc "$file" tmp &> /dev/null
            pattern="tmp/*.xml"
            xml_files=( $pattern )
            xml_file=${xml_files[0]}
        else
            xml_file="$file"
        fi
        unzip -o "$file" -d tmp &> /dev/null
        pattern="tmp/*.xml"
        kern_filename=$(php slugify.php "$(echo "$filename" | sed "s/Schiorring - //")"   )
        num=$(echo "$kern_filename" | grep -o '^[0-9]\+')
        if (( ${#num} < $pad_num )); then
            new_num=$(pad_with_zeros "$num")
            kern_filename="${new_num}${kern_filename#${num}}"
        fi
        kern_filename="$kern_filename.krn"
        echo "$kern_filename"
        musicxml2hum "$xml_file" | extractxx -f 1,3,2,4,5,6,7,8,9 > "kern/$kern_filename"
        # musicxml2hum "$xml_file" > "kern/$kern_filename" 2> /dev/null
    fi
done

rm -rf tmp
